-- Tabela de Horários (Faltou no seu script anterior)
-- Necessária para o funcionamento da agenda

create table if not exists schedules (
  id bigint generated by default as identity primary key,
  tech_id text references users(id),
  date text not null, -- YYYY-MM-DD
  slots jsonb not null default '[]',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(tech_id, date)
);

-- Liberar acesso (Dev)
alter table schedules enable row level security;
create policy "Public Access" on schedules for all using (true);
